// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestManagement.Api.Data;

#nullable disable

namespace TestManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestManagement.Api.Models.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceFamily")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ExpectedTrip")
                        .HasColumnType("boolean");

                    b.Property<int?>("ExpectedTripMaxMs")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpectedTripMinMs")
                        .HasColumnType("integer");

                    b.Property<double>("FaultCurrent")
                        .HasColumnType("double precision");

                    b.Property<int>("FaultStartMs")
                        .HasColumnType("integer");

                    b.Property<string>("FaultType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PickupCurrent")
                        .HasColumnType("double precision");

                    b.Property<string>("ProtectionFunction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TripDelayMs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("TestManagement.Api.Models.TestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("ActualTrip")
                        .HasColumnType("boolean");

                    b.Property<int?>("ActualTripTimeMs")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Passed")
                        .HasColumnType("boolean");

                    b.Property<string>("ResultMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("TestManagement.Api.Models.TestRun", b =>
                {
                    b.HasOne("TestManagement.Api.Models.TestCase", "TestCase")
                        .WithMany("TestRuns")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("TestManagement.Api.Models.TestCase", b =>
                {
                    b.Navigation("TestRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
