name: Build and push frontend image

on:
  push:
    branches: [ "main" ]
    paths:
      - "siprotec-frontend/**"
      - ".github/workflows/build-frontend-ci.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "siprotec-frontend/**"
      - ".github/workflows/build-frontend-ci.yml"

# final image: ghcr.io/justaprog/siprotec-frontend:latest
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: justaprog/siprotec-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./siprotec-frontend
          push: ${{ github.event_name == 'push' }}
          # set image tag to commit sha for traceability
          tags: 
            ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest